### ISSUE TITLE
Dockerfile cannot build

### ISSUE THREAD

**Issue by oerd** [Josh5/docker-rhodecode#1]
Dockerfile cannot build due to incorrect links for downloading VCS and CE packages.
There are two strategies to fix this:

1. remove `--offline` flag when running rccontrol: works better in the long run (when links break again due to Rhodecode rebuilds), but is not "offline"
2. update links periodically: for which I am providing a patch for

**Comment by Josh5** [comment]
Thanks for the patch. For the sake of version control of the container, I would prefer to keep it configured for offline mode.
